name: Rebuild Astro Site
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  trigger_build:
    runs-on: ubuntu-24.04
    steps:
      - name: Trigger Webhook
        run: |
          curl -X POST ${{secrets.WEBHOOK_URL}}
